//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client.BulkUpdate
{
    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class AttendanceImportEntity
    {
        /// <summary />
        public int? AttendanceForeignId { get; set; }

        /// <summary />
        public int? CampusId { get; set; }

        /// <summary />
        public DateTime? EndDateTime { get; set; }

        /// <summary />
        public int? GroupForeignId { get; set; }

        /// <summary />
        public int? LocationForeignId { get; set; }

        /// <summary />
        public string Note { get; set; }

        /// <summary />
        public int PersonForeignId { get; set; }

        /// <summary />
        public int? ScheduleForeignId { get; set; }

        /// <summary />
        public DateTime StartDateTime { get; set; }

        /// <summary>
        /// Copies the base properties from a source AttendanceImport object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( AttendanceImport source )
        {
            this.AttendanceForeignId = source.AttendanceForeignId;
            this.CampusId = source.CampusId;
            this.EndDateTime = source.EndDateTime;
            this.GroupForeignId = source.GroupForeignId;
            this.LocationForeignId = source.LocationForeignId;
            this.Note = source.Note;
            this.PersonForeignId = source.PersonForeignId;
            this.ScheduleForeignId = source.ScheduleForeignId;
            this.StartDateTime = source.StartDateTime;

        }
    }

    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class AttendanceImport : AttendanceImportEntity
    {
    }
}
