//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client.BulkUpdate
{
    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class FinancialBatchImportEntity
    {
        /// <summary />
        public int? CampusId { get; set; }

        /// <summary />
        public decimal ControlAmount { get; set; }

        /// <summary />
        public int? CreatedByPersonForeignId { get; set; }

        /// <summary />
        public DateTime? EndDate { get; set; }

        /// <summary />
        public int FinancialBatchForeignId { get; set; }

        /// <summary />
        public int? ModifiedByPersonForeignId { get; set; }

        /// <summary />
        public string Name { get; set; }

        /// <summary />
        public DateTime? StartDate { get; set; }

        /// <summary />
        public int /* BatchStatus*/ Status { get; set; }

        /// <summary />
        public DateTime? CreatedDateTime { get; set; }

        /// <summary />
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Copies the base properties from a source FinancialBatchImport object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( FinancialBatchImport source )
        {
            this.CampusId = source.CampusId;
            this.ControlAmount = source.ControlAmount;
            this.CreatedByPersonForeignId = source.CreatedByPersonForeignId;
            this.EndDate = source.EndDate;
            this.FinancialBatchForeignId = source.FinancialBatchForeignId;
            this.ModifiedByPersonForeignId = source.ModifiedByPersonForeignId;
            this.Name = source.Name;
            this.StartDate = source.StartDate;
            this.Status = source.Status;
            this.CreatedDateTime = source.CreatedDateTime;
            this.ModifiedDateTime = source.ModifiedDateTime;

        }
    }

    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class FinancialBatchImport : FinancialBatchImportEntity
    {
    }
}
