//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client.BulkImport
{
    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class FinancialTransactionImportEntity
    {
        /// <summary />
        public int? AuthorizedPersonForeignId { get; set; }

        /// <summary />
        public int BatchForeignId { get; set; }

        /// <summary />
        public int? CreatedByPersonForeignId { get; set; }

        /// <summary />
        public int CurrencyTypeValueId { get; set; }

        /// <summary />
        public List<FinancialTransactionDetailImport> FinancialTransactionDetailImports { get; set; }

        /// <summary />
        public int FinancialTransactionForeignId { get; set; }

        /// <summary />
        public int? ModifiedByPersonForeignId { get; set; }

        /// <summary />
        public string Summary { get; set; }

        /// <summary />
        public string TransactionCode { get; set; }

        /// <summary />
        public DateTime? TransactionDate { get; set; }

        /// <summary />
        public int TransactionSourceValueId { get; set; }

        /// <summary />
        public int TransactionTypeValueId { get; set; }

        /// <summary />
        public DateTime? CreatedDateTime { get; set; }

        /// <summary />
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Copies the base properties from a source FinancialTransactionImport object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( FinancialTransactionImport source )
        {
            this.AuthorizedPersonForeignId = source.AuthorizedPersonForeignId;
            this.BatchForeignId = source.BatchForeignId;
            this.CreatedByPersonForeignId = source.CreatedByPersonForeignId;
            this.CurrencyTypeValueId = source.CurrencyTypeValueId;
            this.FinancialTransactionDetailImports = source.FinancialTransactionDetailImports;
            this.FinancialTransactionForeignId = source.FinancialTransactionForeignId;
            this.ModifiedByPersonForeignId = source.ModifiedByPersonForeignId;
            this.Summary = source.Summary;
            this.TransactionCode = source.TransactionCode;
            this.TransactionDate = source.TransactionDate;
            this.TransactionSourceValueId = source.TransactionSourceValueId;
            this.TransactionTypeValueId = source.TransactionTypeValueId;
            this.CreatedDateTime = source.CreatedDateTime;
            this.ModifiedDateTime = source.ModifiedDateTime;

        }
    }

    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class FinancialTransactionImport : FinancialTransactionImportEntity
    {
    }
}
