//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client.BulkImport
{
    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class FinancialTransactionDetailImportEntity
    {
        /// <summary />
        public decimal Amount { get; set; }

        /// <summary />
        public int? CreatedByPersonForeignId { get; set; }

        /// <summary />
        public int? FinancialAccountForeignId { get; set; }

        /// <summary />
        public int FinancialTransactionDetailForeignId { get; set; }

        /// <summary />
        public int? ModifiedByPersonForeignId { get; set; }

        /// <summary />
        public string Summary { get; set; }

        /// <summary />
        public DateTime? CreatedDateTime { get; set; }

        /// <summary />
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Copies the base properties from a source FinancialTransactionDetailImport object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( FinancialTransactionDetailImport source )
        {
            this.Amount = source.Amount;
            this.CreatedByPersonForeignId = source.CreatedByPersonForeignId;
            this.FinancialAccountForeignId = source.FinancialAccountForeignId;
            this.FinancialTransactionDetailForeignId = source.FinancialTransactionDetailForeignId;
            this.ModifiedByPersonForeignId = source.ModifiedByPersonForeignId;
            this.Summary = source.Summary;
            this.CreatedDateTime = source.CreatedDateTime;
            this.ModifiedDateTime = source.ModifiedDateTime;

        }
    }

    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class FinancialTransactionDetailImport : FinancialTransactionDetailImportEntity
    {
    }
}
