//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client.BulkImport
{
    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class PersonImportEntity
    {
        /// <summary />
        public ICollection<PersonAddressImport> Addresses { get; set; }

        /// <summary />
        public DateTime? AnniversaryDate { get; set; }

        /// <summary />
        public ICollection<AttributeValueImport> AttributeValues { get; set; }

        /// <summary />
        public int? BirthDay { get; set; }

        /// <summary />
        public int? BirthMonth { get; set; }

        /// <summary />
        public int? BirthYear { get; set; }

        /// <summary />
        public int? CampusId { get; set; }

        /// <summary />
        public int? ConnectionStatusValueId { get; set; }

        /// <summary />
        public string Email { get; set; }

        /// <summary />
        public string EmailNote { get; set; }

        /// <summary />
        public int EmailPreference { get; set; }

        /// <summary />
        public int? FamilyForeignId { get; set; }

        /// <summary />
        public string FamilyImageUrl { get; set; }

        /// <summary />
        public string FamilyName { get; set; }

        /// <summary />
        public string FirstName { get; set; }

        /// <summary />
        public int Gender { get; set; }

        /// <summary />
        public bool? GivingIndividually { get; set; }

        /// <summary />
        public string Grade { get; set; }

        /// <summary />
        public int? GraduationYear { get; set; }

        /// <summary />
        public int GroupRoleId { get; set; }

        /// <summary />
        public string InactiveReasonNote { get; set; }

        /// <summary />
        public bool IsDeceased { get; set; }

        /// <summary />
        public bool IsEmailActive { get; set; }

        /// <summary />
        public string LastName { get; set; }

        /// <summary />
        public int? MaritalStatusValueId { get; set; }

        /// <summary />
        public string MiddleName { get; set; }

        /// <summary />
        public string NickName { get; set; }

        /// <summary />
        public string Note { get; set; }

        /// <summary />
        public int PersonForeignId { get; set; }

        /// <summary />
        public string PersonPhotoUrl { get; set; }

        /// <summary />
        public ICollection<PhoneNumberImport> PhoneNumbers { get; set; }

        /// <summary />
        public DateTime? RecordStatusLastModifiedDateTime { get; set; }

        /// <summary />
        public int? RecordStatusReasonValueId { get; set; }

        /// <summary />
        public int? RecordStatusValueId { get; set; }

        /// <summary />
        public int? RecordTypeValueId { get; set; }

        /// <summary />
        public int? ReviewReasonValueId { get; set; }

        /// <summary />
        public int? SuffixValueId { get; set; }

        /// <summary />
        public int? TitleValueId { get; set; }

        /// <summary />
        public DateTime? CreatedDateTime { get; set; }

        /// <summary />
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Copies the base properties from a source PersonImport object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( PersonImport source )
        {
            this.Addresses = source.Addresses;
            this.AnniversaryDate = source.AnniversaryDate;
            this.AttributeValues = source.AttributeValues;
            this.BirthDay = source.BirthDay;
            this.BirthMonth = source.BirthMonth;
            this.BirthYear = source.BirthYear;
            this.CampusId = source.CampusId;
            this.ConnectionStatusValueId = source.ConnectionStatusValueId;
            this.Email = source.Email;
            this.EmailNote = source.EmailNote;
            this.EmailPreference = source.EmailPreference;
            this.FamilyForeignId = source.FamilyForeignId;
            this.FamilyImageUrl = source.FamilyImageUrl;
            this.FamilyName = source.FamilyName;
            this.FirstName = source.FirstName;
            this.Gender = source.Gender;
            this.GivingIndividually = source.GivingIndividually;
            this.Grade = source.Grade;
            this.GraduationYear = source.GraduationYear;
            this.GroupRoleId = source.GroupRoleId;
            this.InactiveReasonNote = source.InactiveReasonNote;
            this.IsDeceased = source.IsDeceased;
            this.IsEmailActive = source.IsEmailActive;
            this.LastName = source.LastName;
            this.MaritalStatusValueId = source.MaritalStatusValueId;
            this.MiddleName = source.MiddleName;
            this.NickName = source.NickName;
            this.Note = source.Note;
            this.PersonForeignId = source.PersonForeignId;
            this.PersonPhotoUrl = source.PersonPhotoUrl;
            this.PhoneNumbers = source.PhoneNumbers;
            this.RecordStatusLastModifiedDateTime = source.RecordStatusLastModifiedDateTime;
            this.RecordStatusReasonValueId = source.RecordStatusReasonValueId;
            this.RecordStatusValueId = source.RecordStatusValueId;
            this.RecordTypeValueId = source.RecordTypeValueId;
            this.ReviewReasonValueId = source.ReviewReasonValueId;
            this.SuffixValueId = source.SuffixValueId;
            this.TitleValueId = source.TitleValueId;
            this.CreatedDateTime = source.CreatedDateTime;
            this.ModifiedDateTime = source.ModifiedDateTime;

        }
    }

    /// <summary>
    /// Model for Rock Bulk Insert APIs
    /// </summary>
    public partial class PersonImport : PersonImportEntity
    {
    }
}
